vehicle_parameters:
  max_speed: 10.0
  acceleration: 2.0
  deceleration: 3.0
  turning_radius: 5.0

map_settings:
  map_file: "data/maps/sample_map.yaml"
  grid_size: 0.5
  occupancy_threshold: 0.5

simulation_settings:
  time_step: 0.1
  max_iterations: 1000
  render: true

visualization_settings:
  show_vehicle: true
  show_grid: true
  grid_color: "blue"
  vehicle_color: "red"